# Generated by Django 4.2.3 on 2023-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Este campo deve ser marcado caso queira que a página seja exibida publicamente.'),
        ),
    ]
